import {
  Gem,
  GraduationCap,
  NotebookPen,
  Rocket,
  Briefcase,
  Heart,
  Gamepad2,
  Music,
  BookOpen,
  Code,
  ShoppingBag,
  Home,
  Star,
  Dumbbell,
  PawPrint,
  Dog,
  Cat,
  Car,
  Plane,
  Coffee,
  Utensils,
  Baby,
  Calendar,
  Wallet,
  Camera,
  Palette,
  Lightbulb,
  DollarSign,
  PiggyBank,
  Gift,
  Crown,
  Sparkles,
  Shield,
  Scissors,
  Stethoscope,
  ClipboardCheck,
  PenTool,
  Sun,
  Moon,
  TreePine,
  Flower2,
  Users,
  Medal,
  Trophy,
  Timer,
  AlarmClock,
  Wrench,
  Hammer,
  Phone,
  Bus,
  Bike,
  UtensilsCrossed,
  Landmark,
  Pill,
  Shirt,
  Laptop,
  type LucideIcon,
} from 'lucide-react'
import type { SectionMeta } from '../types/task'

export const DEFAULT_SECTIONS: SectionMeta[] = [
  { id: 'trabajo', label: 'Trabajo', icon: 'briefcase', order: 0 },
  { id: 'universidad', label: 'Universidad', icon: 'graduation-cap', order: 1 },
  { id: 'diario', label: 'Diario', icon: 'notebook-pen', order: 2 },
]

export const LEGACY_SECTION_IDS: Record<string, string> = {
  gem: 'trabajo',
  uni: 'universidad',
}

export function migrateSectionId(id: string): string {
  return LEGACY_SECTION_IDS[id] ?? id
}

export const ICON_MAP: Record<string, LucideIcon> = {
  gem: Gem,
  'graduation-cap': GraduationCap,
  'notebook-pen': NotebookPen,
  rocket: Rocket,
  briefcase: Briefcase,
  heart: Heart,
  'gamepad-2': Gamepad2,
  music: Music,
  'book-open': BookOpen,
  code: Code,
  'shopping-bag': ShoppingBag,
  home: Home,
  star: Star,
  dumbbell: Dumbbell,
  'paw-print': PawPrint,
  dog: Dog,
  cat: Cat,
  car: Car,
  plane: Plane,
  coffee: Coffee,
  utensils: Utensils,
  baby: Baby,
  calendar: Calendar,
  wallet: Wallet,
  camera: Camera,
  palette: Palette,
  lightbulb: Lightbulb,
  'dollar-sign': DollarSign,
  'piggy-bank': PiggyBank,
  gift: Gift,
  crown: Crown,
  sparkles: Sparkles,
  shield: Shield,
  scissors: Scissors,
  stethoscope: Stethoscope,
  'clipboard-check': ClipboardCheck,
  'pen-tool': PenTool,
  sun: Sun,
  moon: Moon,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  users: Users,
  medal: Medal,
  trophy: Trophy,
  timer: Timer,
  'alarm-clock': AlarmClock,
  wrench: Wrench,
  hammer: Hammer,
  phone: Phone,
  bus: Bus,
  bike: Bike,
  'utensils-crossed': UtensilsCrossed,
  landmark: Landmark,
  pill: Pill,
  shirt: Shirt,
  laptop: Laptop,
}

export const SECTION_ICONS: { key: string; label: string }[] = [
  { key: 'gem', label: 'Gema' },
  { key: 'graduation-cap', label: 'Universidad' },
  { key: 'notebook-pen', label: 'Diario' },
  { key: 'rocket', label: 'Rocket' },
  { key: 'briefcase', label: 'Trabajo' },
  { key: 'laptop', label: 'Computador' },
  { key: 'code', label: 'Código' },
  { key: 'shopping-bag', label: 'Compras' },
  { key: 'wallet', label: 'Billetera' },
  { key: 'piggy-bank', label: 'Ahorros' },
  { key: 'dollar-sign', label: 'Dinero' },
  { key: 'heart', label: 'Corazón' },
  { key: 'home', label: 'Hogar' },
  { key: 'dog', label: 'Perro' },
  { key: 'cat', label: 'Gato' },
  { key: 'paw-print', label: 'Mascotas' },
  { key: 'car', label: 'Carro' },
  { key: 'bus', label: 'Bus' },
  { key: 'bike', label: 'Bicicleta' },
  { key: 'plane', label: 'Viajes' },
  { key: 'coffee', label: 'Café' },
  { key: 'utensils', label: 'Comida' },
  { key: 'utensils-crossed', label: 'Restaurante' },
  { key: 'baby', label: 'Bebé' },
  { key: 'calendar', label: 'Calendario' },
  { key: 'camera', label: 'Fotos' },
  { key: 'palette', label: 'Arte' },
  { key: 'lightbulb', label: 'Ideas' },
  { key: 'pen-tool', label: 'Diseño' },
  { key: 'book-open', label: 'Libro' },
  { key: 'music', label: 'Música' },
  { key: 'gamepad-2', label: 'Juego' },
  { key: 'dumbbell', label: 'Gimnasio' },
  { key: 'shirt', label: 'Ropa' },
  { key: 'scissors', label: 'Belleza' },
  { key: 'stethoscope', label: 'Salud' },
  { key: 'pill', label: 'Medicinas' },
  { key: 'clipboard-check', label: 'Listas' },
  { key: 'landmark', label: 'Trámites' },
  { key: 'gift', label: 'Regalo' },
  { key: 'crown', label: 'Corona' },
  { key: 'sparkles', label: 'Estrellas' },
  { key: 'shield', label: 'Seguridad' },
  { key: 'users', label: 'Equipo' },
  { key: 'medal', label: 'Logros' },
  { key: 'trophy', label: 'Trofeo' },
  { key: 'timer', label: 'Cronómetro' },
  { key: 'alarm-clock', label: 'Alarma' },
  { key: 'sun', label: 'Sol' },
  { key: 'moon', label: 'Luna' },
  { key: 'tree-pine', label: 'Naturaleza' },
  { key: 'flower-2', label: 'Plantas' },
  { key: 'wrench', label: 'Arreglos' },
  { key: 'hammer', label: 'Construcción' },
  { key: 'phone', label: 'Teléfono' },
  { key: 'star', label: 'Estrella' },
]

export function makeSectionId(label: string, existing: string[]): string {
  const base =
    label
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 24) || 'apartado'
  let id = base
  let i = 2
  while (existing.includes(id)) id = `${base}-${i++}`
  return id
}
